language: python

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - python  manyfesto/test_manyfesto.py
  - python -m coverage run manyfesto/test_manyfesto.py
  - COVERALLS_REPO_TOKEN=MtSS6YjmlOAU13T847YDRVuMotNOAGMQJ
  - coveralls